### PR TITLE
Incorporate groups + bug fix

### PR DESCRIPTION
**Pull request by groupsixtech**
Add groups to position registers
Add groups to position data json
Added "FINE" movement to termination when term(-1)
Fixed timer bug
Fixed DIV bug

### CODE REVIEW

**Comment by unreal** [comment]
Hey Matt,

Thanks for the pull request! I checked it out, but there are a few issues:
1. Please add test cases for any new features or fixes and make sure the full test suite passes. It seems like you already have the dependencies, but you can always get them with `bundle`, and then the test suite can be run with `rake`. The "Ruby way" is generally to 1) add failing test case, 2) run tests to verify test fails, 3) add code, 4) see passing test case.
2. I like using `term(-1)` for `FINE`, but it looks like the comparison should be `>= 0`. See failing tests. (Obviously I never use FINE since I never supported this!)
3. You'll see some failing tests after removing the comment. We should update the tests to reflect that the comment should not be present since `maketp` and the ASCII upload option fail with the comment present. (We should probably put a comment there too to remind ourselves).
4. Regarding multi-group, I think we need to discuss the requirements and make sure we cover everything:
   1. TP+ position data needs to include additional groups, and the parser needs to parse this data
   2. We need the ability to specify the group when assigning PR components.
   3. We need to specify the correct group mask in the TP header data when generating the LS file

Is that it?

Looks like you've solved item 1 by adding a `mask` array to the `position_data` JSON. I like this, but is the UFRAME and UTOOL data necessary for a position data specified with JOINT representation? I believe we need to support JOINT representation in GP1 as well.

I see you added the `group()` method to specify the group on PR component assignment. I'm just wondering if we need to revamp this whole mechanism now that multi-group is in the mix. Seems to me that GP1 will be used 99% of the time, so I would rather not have to add the `group()` every time. Maybe my opinion is tainted from my thoughts on the next version, but maybe we should get rid of `foo.x`, `foo.y`, etc. all together in favor of a built-in like `set_component()`. It would certainly simply the parser. What do you think?

Regarding the group mask header, I added some support for this via the `TP_GROUPMASK` keyword e.g. `TP_GROUPMASK = "*,*,*,*,*"`. At this point we assume `"1,*,*,*,*"` unless otherwise, which seems to be what FANUC's utilities also do. Should we instead make assumptions based on the position data? Should we warn the user or throw an error if they try to access an extended group without specifying the header?

Thanks again for your work on this. You may also want to update your local branch against this one, since I just pushed a change to fix that multiple boolean operator bug.

**Comment by groupsixtech** [comment]
Hey Jay,

I've run a rake, and all of the test cases pass with our recent updates. I have updated the termination node to fix that error (my bad). I haven't put anything into the failing test cases that's my next step. I further fixed the mixed logic based on your bug fix. It still didn't flip conditionals (e.g. foo==1 && foo==2 turned out to be foo<>1 OR foo ==2 instead of foo<>1 OR foo <>2). I fixed that with modifying that else block. Hopefully I didnt screw anything up, but all the test cases passed so I'm optimistic. 

I'll check the JOINT representation in GP1. I think I made it so if the mask array isnt included it only uses GP1. All of your previous test for positional data still clear. I had to update the spacing though because it changed with my additions. 

You do not need to include group in the component assignment foo.x, and foo.y still pass. Auto assigning TP_GROUPMASK would be a good thing if possible. I think it depends if you've included the position data in the tpp. I know sometimes I just copy and paste teach points from another program after I've compiled the .ls file. If you do it that way there is no way to infer which groups are being used. But I know I've face palmed a couple time from not remembering to include the correct group masks.

**Comment by unreal** [comment]
Weird that all your tests are passing, because I'm still getting a few failures. I also had a merge conflict after pulling down your latest changes. In the future, you should use `git pull` on the https://github.com/onerobotics/tp_plus.git remote branch to pull in my changes.

Here's the console output from `rake` on my laptop:

```
Loaded suite /Users/jay/.gem/ruby/2.1.1/gems/rake-10.2.2/lib/rake/rake_test_loader
Started
...............................................................................
.................................N
===============================================================================
TestInterpreter#test_position_data_populates_interpreter_position_data was redefined [test_position_data_populates_interpreter_position_data(TestInterpreter)]
/Users/jay/dev/tp+/test/tp_plus/test_interpreter.rb:1182:in `<class:TestInterpreter>'
===============================================================================
......................N
===============================================================================
TestInterpreter#test_simple_linear_motion was redefined [test_simple_linear_motion(TestInterpreter)]
/Users/jay/dev/tp+/test/tp_plus/test_interpreter.rb:1225:in `<class:TestInterpreter>'
===============================================================================
................F
===============================================================================
Failure:
test_timer_reset(TestInterpreter)
/Users/jay/dev/tp+/test/tp_plus/test_interpreter.rb:26:in `assert_prog'
/Users/jay/dev/tp+/test/tp_plus/test_interpreter.rb:798:in `test_timer_reset'
     795: 
     796:   def test_timer_reset
     797:     parse "foo := TIMER[1]\nreset foo"
  => 798:     assert_prog "TIMER[1:foo]=RESET ;\n"
     799:   end
     800: 
     801:   def test_timer_stop
<"TIMER[1:foo]=RESET ;\n"> expected but was
<"TIMER[1]=RESET ;\n">

diff:
? TIMER[1:foo]=RESET ;
===============================================================================
F
===============================================================================
Failure:
test_timer_restart(TestInterpreter)
/Users/jay/dev/tp+/test/tp_plus/test_interpreter.rb:26:in `assert_prog'
/Users/jay/dev/tp+/test/tp_plus/test_interpreter.rb:808:in `test_timer_restart'
     805: 
     806:   def test_timer_restart
     807:     parse "foo := TIMER[1]\nrestart foo"
  => 808:     assert_prog "TIMER[1:foo]=STOP ;\nTIMER[1:foo]=RESET ;\nTIMER[1:foo]=START ;\n"
     809:   end
     810: 
     811:   def test_indirect_timer
<"TIMER[1:foo]=STOP ;\nTIMER[1:foo]=RESET ;\nTIMER[1:foo]=START ;\n"> expected but was
<"TIMER[1]=STOP ;\nTIMER[1]=RESET ;\nTIMER[1]=START ;\n">

diff:
? TIMER[1:foo]=STOP ;
? TIMER[1:foo]=RESET ;
? TIMER[1:foo]=START ;
===============================================================================
F
===============================================================================
Failure:
test_timer_start(TestInterpreter)
/Users/jay/dev/tp+/test/tp_plus/test_interpreter.rb:26:in `assert_prog'
/Users/jay/dev/tp+/test/tp_plus/test_interpreter.rb:793:in `test_timer_start'
     790: 
     791:   def test_timer_start
     792:     parse "foo := TIMER[1]\nstart foo"
  => 793:     assert_prog "TIMER[1:foo]=START ;\n"
     794:   end
     795: 
     796:   def test_timer_reset
<"TIMER[1:foo]=START ;\n"> expected but was
<"TIMER[1]=START ;\n">

diff:
? TIMER[1:foo]=START ;
===============================================================================
F
===============================================================================
Failure:
test_timer_stop(TestInterpreter)
/Users/jay/dev/tp+/test/tp_plus/test_interpreter.rb:26:in `assert_prog'
/Users/jay/dev/tp+/test/tp_plus/test_interpreter.rb:803:in `test_timer_stop'
     800: 
     801:   def test_timer_stop
     802:     parse "foo := TIMER[1]\nstop foo"
  => 803:     assert_prog "TIMER[1:foo]=STOP ;\n"
     804:   end
     805: 
     806:   def test_timer_restart
<"TIMER[1:foo]=STOP ;\n"> expected but was
<"TIMER[1]=STOP ;\n">

diff:
? TIMER[1:foo]=STOP ;
===============================================================================
...............................................................................
...............................................................................
......................................................

Finished in 0.613673 seconds.

366 tests, 393 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 2 notifications
98.9071% passed

596.41 tests/s, 640.41 assertions/s
```

Looks like the timer tests need to get updated, and there are a couple of duplicate test method names.

> It still didn't flip conditionals (e.g. foo==1 && foo==2 turned out to be foo<>1 OR foo ==2 instead of foo<>1 OR foo <>2).

Ahhh, I didn't realize it wasn't flipping the operators since I only tested Flags. Good catch. We should also make test cases for `unless.`

I'm not sure this is the best syntax. How do we set GP2 components?

```
foo := PR[1]
foo.group(1).y=5
```

What about:

```
foo := PR[1]
# PR[GP1:1,1:foo]=5 ;
set_component(foo, 'x', 5) 
# PR[GP2:1,1:foo]=20 ;
set_component(foo, 'j1', 20, 2)
```

> Auto assigning TP_GROUPMASK would be a good thing if possible.

It's possible since the entire program is parsed before the LS output is generated. I think we should handle this in a separate issue/pull-request. It would be nice if the TP_GROUPMASK line was not necessary at all. TP+ should be smart enough to know if anything other than "_,_,_,_,*" is necessary.

> I know sometimes I just copy and paste teach points from another program after I've compiled the .ls file. If you do it that way there is no way to infer which groups are being used. But I know I've face palmed a couple time from not remembering to include the correct group masks.

This is probably another discussion too, but I personally think TP+ should warn you if you're using positions that have no data associated with them. Perhaps an option flag to even fail unless the data is present e.g. tpp --strict filename.tpp

**Comment by gavanderhoorn** [comment]
On 6-3-2015 4:56, Jay Strybis wrote:

> I'm not sure this is the best syntax. How do we set GP2 components?
> 
> ```
> foo := PR[1]
> foo.group(1).y=5
> ```
> 
> What about:
> 
> ```
> foo := PR[1]
> # PR[GP1:1,1:foo]=5 ;
> set_component(foo, 'x', 5) 
> # PR[GP2:1,1:foo]=20 ;
> set_component(foo, 'j1', 20, 2)
> ```

Perhaps:

  foo := PR[1]

  # default group 1 accessor
  foo.x = 5

  # or
  foo.g1.x = 5

  # other groups
  foo.g2.j1 = 20

Just treat it like a compound data type? 'set_component(..)' seems to
deviate (style-wise) from the rest of TPP.

**Comment by gavanderhoorn** [comment]
O, just noticed that your initial quote already included something similar. Nevermind. Sorry for the noise.

**Comment by unreal** [comment]
> Just treat it like a compound data type? 'set_component(..)' seems to deviate (style-wise) from the rest of TPP.

Yes I agree. While TP+ was heavily influenced by Ruby, my new opinions are heavily influenced by Golang. It makes sense to keep this version (for what it's worth) ruby-esque.

I've been thinking about the group assignment a bit more:
1. TP lets you indirectly assign PR components. The current implementation of TP+ does not. Is this a problem? e.g. `PR[R[1],R[2]]=R[3]`
2. I like the `foo.g2.j1` suggestion made by Gijs, but I also like the ability to include use a constant as in the `foo.group(x).j1` syntax. It may be confusing that you can only use an integer or constant here (no numregs allowed since TP does not support it), but we can throw a parse error... Would anyone ever actually use a constant there? If not, I think we should go with `gX`, `grpX` or `groupX` over `group(X)`.

> I'll check the JOINT representation in GP1. I think I made it so if the mask array isnt included it only uses GP1.

I think we should use a consistent representation of the position data whether it's multi-group or not. i.e. we should always include the mask array.

**Comment by groupsixtech** [comment]
I changed the syntax to g1,g2 etc... but you may not like how I've done it because I had to use regex for the token. It was a complete cluster F**k trying to merge your commits from the past few days so it would be great to get both of these repos on the same page. There may be some conflicts. I'll try another pull request.

**Pull request closed without merging**
