### PR TITLE
pr groups + positional groups #3

### PR DESCRIPTION
**Pull request by groupsixtech**

### CODE REVIEW

**Comment by unreal** [comment]
Hey Matt,

Thanks for the new pull request. However, it's difficult to merge into master when the pull request contains many commits and some of them do not pass the test suite. Generally, I only commit once the test suite is passing.

Also, in the future, use `git rebase` to bring in my changes that have been added while you've been working. This will yield a cleaner history in the repository. Here's a useful article on that: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

I'll pull down your branch and see about fixing the test suite so we can move forward!

**Comment by groupsixtech** [comment]
ok. The tests that don't pass are actually ones I've added that dont pass
on the master either. The brackets are messed up on the if statements in
certain instances. I'll try and pinpoint the issue when I have the chance,
but just want to make you aware of it.

On Thu, Mar 12, 2015 at 8:01 AM, Jay Strybis notifications@github.com
wrote:

> Hey Matt,
> 
> Thanks for the new pull request. However, it's difficult to merge into
> master when the pull request contains many commits and some of them do not
> pass the test suite. Generally, I only commit once the test suite is
> passing.
> 
> Also, in the future, use git rebase to bring in my changes that have been
> added while you've been working. This will yield a cleaner history in the
> repository. Here's a useful article on that:
> https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
> 
> I'll pull down your branch and see about fixing the test suite so we can
> move forward!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/onerobotics/tp_plus/pull/4#issuecomment-78484449.

## 

[image: GroupSix_Logo]

Matthew Dewar, EIT.

Materials/Process Engineer

C: 780-802-9162

www.groupsixtech.com

Follow us on LinkedIn:

Group Six Technologies: LinkedIn
https://www.linkedin.com/company/3676534?trk=prof-exp-company-name

**Comment by unreal** [comment]
I went through and rebased this pull request against master, doing some refactoring here and there, adding tests, etc. ea813e723bb404c697d40636bd3efc8a790715fa

Some heavy refactoring inside ExpressionNode (the whole parens thing, operator flipping thing is a pain). Maybe at some point we should just use `IF THEN ENDIF` syntax since TP now supports it.

You may want to create a new fork against the main repo, since I believe it is up to date at this point.

**Comment by groupsixtech** [comment]
... I guess you could call that refactoring.... hahaha. I think I contributed like 3 lines of clean code, the rest was pretty messy. I'm pretty much a monkey with a keyboard at this point. Hopefully I'll get better and you wont have to "refactor" what I contribute.

Awesome work by the way. You are a machine. 

Yeah conditional statements are definitely the worst part about this...

**Comment by unreal** [comment]
Ha, it was mostly just changing things into more idiomatic ruby and fixing some of the spots where we committed the same code in two places.

For idiomatic ruby, check out this style guide: https://github.com/bbatsov/ruby-style-guide. I'm sure there are plenty of places in the code that violate the guide, so any pull requests that fix those sorts of issues are also welcome!

Re: committing code in two places, just remember to `git rebase` when your repo is missing some commits from master instead of merging them in manually.

Watch out for shift/reduce and reduce/reduce conflicts in the parser. I think at this point there are 21 shift/reduce conflicts. This indicates that the grammar is ambiguous in a few places. I'd love to get this down to 0, but I think it's mostly due to using a newline (optionally) as a line-ending. At some point I'd like to support terminating statements with a semicolon and make the scanner smart enough to insert semicolons automatically when necessary (so we don't have to write them ourselves).

Also FYI I just pushed an improvement to parse error reporting (correctly reports line and column of the offending token).

**Comment by groupsixtech** [comment]
I'm noticing more bugs creeping in since the recent updates. The expression
node had one, I tried to fix it (see my repo). the mask hash had one as
well which I fixed.

Ones I havent fixed yet.

There is a bug where you cant have digits in labels.

And then there is this one, but I have no idea what the actual problem is.

C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/tp_plus-0.0.75/lib/tp_plus/parser.rb:37:i
n `on_error': Parse error on line 73 column 1: "" (NEWLINE)
(TPPlus::Parser::Par
seError)
        from C:/Ruby21-x64/lib/ruby/2.1.0/racc/parser.rb:258:in
`_racc_do_parse_
c'
        from C:/Ruby21-x64/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
        from
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/tp_plus-0.0.75/lib/tp_plus/p
arser.rb:32:in`parse'
        from
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/tp_plus-0.0.75/bin/tpp:45:in
 `<top (required)>'
        from C:/Ruby21-x64/bin/tpp:23:in`load'
        from C:/Ruby21-x64/bin/tpp:23:in `<main>'

On Thu, Mar 12, 2015 at 1:10 PM, Jay Strybis notifications@github.com
wrote:

> Ha, it was mostly just changing things into more idiomatic ruby and fixing
> some of the spots where we committed the same code in two places.
> 
> For idiomatic ruby, check out this style guide:
> https://github.com/bbatsov/ruby-style-guide. I'm sure there are plenty of
> places in the code that violate the guide, so any pull requests that fix
> those sorts of issues are also welcome!
> 
> Re: committing code in two places, just remember to git rebase when your
> repo is missing some commits from master instead of merging them in
> manually.
> 
> Watch out for shift/reduce and reduce/reduce conflicts in the parser. I
> think at this point there are 21 shift/reduce conflicts. This indicates
> that the grammar is ambiguous in a few places. I'd love to get this down to
> 0, but I think it's mostly due to using a newline (optionally) as a
> line-ending. At some point I'd like to support terminating statements with
> a semicolon and make the scanner smart enough to insert semicolons
> automatically when necessary (so we don't have to write them ourselves).
> 
> Also FYI I just pushed an improvement to parse error reporting (correctly
> reports line and column of the offending token).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/onerobotics/tp_plus/pull/4#issuecomment-78574418.

## 

[image: GroupSix_Logo]

Matthew Dewar, EIT.

Materials/Process Engineer

C: 780-802-9162

www.groupsixtech.com

Follow us on LinkedIn:

Group Six Technologies: LinkedIn
https://www.linkedin.com/company/3676534?trk=prof-exp-company-name

**Comment by groupsixtech** [comment]
So I think it was just late last night for me. I added digits to labels.
idk if you didn't add that because it conflicts with anything but the rake
passed. The other error was just me missing a bracket so dont worry about
that. The only outstanding item is what I added to the expression node in
my repo. Its pretty hacky but I dont know a better way to get around that
bug.

Anyways, also thanks a ton for adding that error reporting helps a lot!

Cheers,

Matt

On Thu, Mar 12, 2015 at 8:39 PM, Matt Dewar matt@groupsixtech.com wrote:

> I'm noticing more bugs creeping in since the recent updates. The
> expression node had one, I tried to fix it (see my repo). the mask hash had
> one as well which I fixed.
> 
> Ones I havent fixed yet.
> 
> There is a bug where you cant have digits in labels.
> 
> And then there is this one, but I have no idea what the actual problem is.
> 
> C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/tp_plus-0.0.75/lib/tp_plus/parser.rb:37:i
> n `on_error': Parse error on line 73 column 1: "" (NEWLINE)
> (TPPlus::Parser::Par
> seError)
>         from C:/Ruby21-x64/lib/ruby/2.1.0/racc/parser.rb:258:in
> `_racc_do_parse_
> c'
>         from C:/Ruby21-x64/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
>         from
> C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/tp_plus-0.0.75/lib/tp_plus/p
> arser.rb:32:in`parse'
>         from
> C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/tp_plus-0.0.75/bin/tpp:45:in
>  `<top (required)>'
>         from C:/Ruby21-x64/bin/tpp:23:in`load'
>         from C:/Ruby21-x64/bin/tpp:23:in `<main>'
> 
> On Thu, Mar 12, 2015 at 1:10 PM, Jay Strybis notifications@github.com
> wrote:
> 
> > Ha, it was mostly just changing things into more idiomatic ruby and
> > fixing some of the spots where we committed the same code in two places.
> > 
> > For idiomatic ruby, check out this style guide:
> > https://github.com/bbatsov/ruby-style-guide. I'm sure there are plenty
> > of places in the code that violate the guide, so any pull requests that fix
> > those sorts of issues are also welcome!
> > 
> > Re: committing code in two places, just remember to git rebase when your
> > repo is missing some commits from master instead of merging them in
> > manually.
> > 
> > Watch out for shift/reduce and reduce/reduce conflicts in the parser. I
> > think at this point there are 21 shift/reduce conflicts. This indicates
> > that the grammar is ambiguous in a few places. I'd love to get this down to
> > 0, but I think it's mostly due to using a newline (optionally) as a
> > line-ending. At some point I'd like to support terminating statements with
> > a semicolon and make the scanner smart enough to insert semicolons
> > automatically when necessary (so we don't have to write them ourselves).
> > 
> > Also FYI I just pushed an improvement to parse error reporting (correctly
> > reports line and column of the offending token).
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/onerobotics/tp_plus/pull/4#issuecomment-78574418.
> 
> ## 
> 
> [image: GroupSix_Logo]
> 
> Matthew Dewar, EIT.
> 
> Materials/Process Engineer
> 
> C: 780-802-9162
> 
> www.groupsixtech.com
> 
> Follow us on LinkedIn:
> 
> Group Six Technologies: LinkedIn
> https://www.linkedin.com/company/3676534?trk=prof-exp-company-name

## 

[image: GroupSix_Logo]

Matthew Dewar, EIT.

Materials/Process Engineer

C: 780-802-9162

www.groupsixtech.com

Follow us on LinkedIn:

Group Six Technologies: LinkedIn
https://www.linkedin.com/company/3676534?trk=prof-exp-company-name

**Comment by unreal** [comment]
Looks like there are a couple spots where our repositories have diverged (ignore `lib/tp_plus/parser.rb` and `lib/tp_plus/parser.output`, etc.), and I think it's causing issues that make it difficult to merge your changes.

I think it best to re-fork this repository and use feature branches (e.g. `git checkout -b my-new-branch) for any bugfixes, new features, etc. That way each pull request will reference a unique branch only relevant to that specific pull request.

Regarding including numbers in label definitions, that's just an oversight! Realistically the label identifier could probably be `/@[a-zA-Z][a-zA-Z_0-9]*/` (start with a letter, then any # of letters, numbers, underscores). Can you create a new pull request from this repo that only implements this change? Basically exactly what you did here https://github.com/groupsixtech/tp_plus/commit/794eb9f7993ff06327539ce6abc924cb5b2fbcda but the commit should ignore `lib/tp_plus/parser.rb` and let's allow underscores as well.

**Comment by unreal** [comment]
> The only outstanding item is what I added to the expression node in
> my repo. Its pretty hacky but I dont know a better way to get around that
> bug.

Can you create an issue that describes the bug?

**Pull request closed without merging**
